services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb://localhost:27017/pong-it
      - NODE_ENV=production
      # Optional: Add for staked match signature generation
      # - SIGNING_WALLET_PRIVATE_KEY=your_private_key_here
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 