services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FRONTEND_URL=http://localhost:3000
      - PLAYER_SERVICE_URL=http://player-service:5001
      - NODE_ENV=production
    depends_on:
      player-service:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

  player-service:
    build: ./player-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://backend:8080
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 